// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF5vM8Jv9pQBQmWDMALzlIBJILoi3mVz8',
    appId: '1:589299917168:web:ef792769f23039e007efb5',
    messagingSenderId: '589299917168',
    projectId: 'play-arena-e71ef',
    authDomain: 'play-arena-e71ef.firebaseapp.com',
    storageBucket: 'play-arena-e71ef.firebasestorage.app',
    measurementId: 'G-C14JBGJDCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApNb5ZTkagPr0YmqIsj3B0kJOyPapBzVs',
    appId: '1:589299917168:android:64eb00d446c24ad207efb5',
    messagingSenderId: '589299917168',
    projectId: 'play-arena-e71ef',
    storageBucket: 'play-arena-e71ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUJy2owkI8k8IwDVn5zApo4epMLthTtgg',
    appId: '1:589299917168:ios:9828732eb0713d4f07efb5',
    messagingSenderId: '589299917168',
    projectId: 'play-arena-e71ef',
    storageBucket: 'play-arena-e71ef.firebasestorage.app',
    iosClientId: '589299917168-v337qfdjp8a7gpn27i3hc2kq6bdo4gu0.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamebooking',
  );
}
